openapi: 3.0.3
info:
    title: The Forecaster Service API
    description: A fast US weather forecast service API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for Weather Forecaster Service API
paths:
    /forecast/{state}/{city}:
        get:
            tags:
                - Forecaster
            summary: forecast Forecaster
            description: Retrieve weather forecast for a given US city
            operationId: Forecaster#forecast
            parameters:
                - name: state
                  in: path
                  description: State
                  required: true
                  schema:
                    type: string
                    description: State
                    example: CA
                    minLength: 2
                    maxLength: 2
                  example: CA
                - name: city
                  in: path
                  description: City
                  required: true
                  schema:
                    type: string
                    description: City
                    example: Santa Barbara
                  example: Santa Barbara
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Forecast'
                            example:
                                location:
                                    city: Santa Barbara
                                    lat: 34.4237458
                                    long: -119.7049146
                                    state: CA
                                periods:
                                    - endTime: "2020-01-01T00:00:00Z"
                                      name: Morning
                                      startTime: "2020-01-01T00:00:00Z"
                                      summary: Clear
                                      temperature: 70
                                      temperatureUnit: F
                                    - endTime: "2020-01-01T00:00:00Z"
                                      name: Morning
                                      startTime: "2020-01-01T00:00:00Z"
                                      summary: Clear
                                      temperature: 70
                                      temperatureUnit: F
                                    - endTime: "2020-01-01T00:00:00Z"
                                      name: Morning
                                      startTime: "2020-01-01T00:00:00Z"
                                      summary: Clear
                                      temperature: 70
                                      temperatureUnit: F
                "504":
                    description: 'timeout: Timeout retrieving forecast'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: Timeout retrieving forecast
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Forecast:
            type: object
            properties:
                location:
                    $ref: '#/components/schemas/Location'
                periods:
                    type: array
                    items:
                        $ref: '#/components/schemas/Period'
                    description: Weather forecast periods
                    example:
                        - endTime: "2020-01-01T00:00:00Z"
                          name: Morning
                          startTime: "2020-01-01T00:00:00Z"
                          summary: Clear
                          temperature: 70
                          temperatureUnit: F
                        - endTime: "2020-01-01T00:00:00Z"
                          name: Morning
                          startTime: "2020-01-01T00:00:00Z"
                          summary: Clear
                          temperature: 70
                          temperatureUnit: F
            example:
                location:
                    city: Santa Barbara
                    lat: 34.4237458
                    long: -119.7049146
                    state: CA
                periods:
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
            required:
                - location
                - periods
        Location:
            type: object
            properties:
                city:
                    type: string
                    description: City
                    example: Santa Barbara
                lat:
                    type: number
                    description: Latitude
                    example: 34.4237458
                    format: double
                long:
                    type: number
                    description: Longitude
                    example: -119.7049146
                    format: double
                state:
                    type: string
                    description: State
                    example: CA
            description: Geographical location
            example:
                city: Santa Barbara
                lat: 34.4237458
                long: -119.7049146
                state: CA
            required:
                - lat
                - long
                - city
                - state
        Period:
            type: object
            properties:
                endTime:
                    type: string
                    description: End time
                    example: "2020-01-01T00:00:00Z"
                    format: date-time
                name:
                    type: string
                    description: Period name
                    example: Morning
                startTime:
                    type: string
                    description: Start time
                    example: "2020-01-01T00:00:00Z"
                    format: date-time
                summary:
                    type: string
                    description: Summary
                    example: Clear
                temperature:
                    type: integer
                    description: Temperature
                    example: 70
                    format: int64
                temperatureUnit:
                    type: string
                    description: Temperature unit
                    example: F
            description: Weather forecast period
            example:
                endTime: "2020-01-01T00:00:00Z"
                name: Morning
                startTime: "2020-01-01T00:00:00Z"
                summary: Clear
                temperature: 70
                temperatureUnit: F
            required:
                - name
                - startTime
                - endTime
                - temperature
                - temperatureUnit
                - summary
tags:
    - name: Forecaster
      description: Service that provides weather forecasts
