swagger: "2.0"
info:
    title: The Poller Service API
    description: US weather forecast poller service API
    version: ""
host: localhost:80
basePath: /poller
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /location:
        post:
            tags:
                - Poller
            summary: add_location Poller
            description: Adds a location to the polling list.
            operationId: Poller#add_location
            parameters:
                - name: city
                  in: query
                  description: City
                  required: true
                  type: string
                - name: state
                  in: query
                  description: State
                  required: true
                  type: string
                  maxLength: 2
                  minLength: 2
            responses:
                "202":
                    description: Accepted response.
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/PollerAddLocationLocationExistsResponseBody'
            schemes:
                - http
    /status:
        get:
            tags:
                - Poller
            summary: status Poller
            description: Provides poller status and statistics.
            operationId: Poller#status
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PollerStatusResponseBody'
                        required:
                            - workers
                            - jobs
            schemes:
                - http
    /subscribe:
        get:
            tags:
                - Poller
            summary: subscribe Poller
            description: Subscribes to weather forecast notifications for a location.
            operationId: Poller#subscribe
            parameters:
                - name: city
                  in: query
                  description: City
                  required: true
                  type: string
                - name: state
                  in: query
                  description: State
                  required: true
                  type: string
                  maxLength: 2
                  minLength: 2
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/PollerSubscribeResponseBody'
                        required:
                            - location
                            - periods
            schemes:
                - ws
    /workers:
        post:
            tags:
                - Poller
            summary: add_worker Poller
            description: Adds a worker to the poller worker pool.
            operationId: Poller#add_worker
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PollerAddWorkerResponseBody'
                        required:
                            - id
                            - jobs
                            - created_at
            schemes:
                - http
        delete:
            tags:
                - Poller
            summary: remove_worker Poller
            description: Removes a worker from the poller worker pool.
            operationId: Poller#remove_worker
            responses:
                "204":
                    description: No Content response.
                "417":
                    description: Expectation Failed response.
                    schema:
                        $ref: '#/definitions/PollerRemoveWorkerTooFewResponseBody'
            schemes:
                - http
definitions:
    JobResponseBody:
        title: JobResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: Creation timestamp
                example: "2020-09-01T12:00:00Z"
            key:
                type: string
                description: Job key
                example: "1"
            payload:
                type: string
                description: Job payload
                example:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
                format: byte
        description: Location forecast poll job
        example:
            created_at: "2020-09-01T12:00:00Z"
            key: "1"
            payload:
                - 123
                - 34
                - 115
                - 116
                - 97
                - 116
                - 101
                - 34
                - 58
                - 34
                - 67
                - 65
                - 34
                - 44
                - 34
                - 99
                - 105
                - 116
                - 121
                - 34
                - 58
                - 34
                - 83
                - 97
                - 110
                - 116
                - 97
                - 32
                - 66
                - 97
                - 114
                - 98
                - 97
                - 114
                - 97
                - 34
                - 125
        required:
            - key
            - payload
            - created_at
    LocationResponseBody:
        title: LocationResponseBody
        type: object
        properties:
            city:
                type: string
                description: City
                example: Santa Barbara
            lat:
                type: number
                description: Latitude
                example: 34.4237458
                format: double
            long:
                type: number
                description: Longitude
                example: -119.7049146
                format: double
            state:
                type: string
                description: State
                example: CA
        description: Geographical location
        example:
            city: Santa Barbara
            lat: 34.4237458
            long: -119.7049146
            state: CA
        required:
            - lat
            - long
            - city
            - state
    PeriodResponseBody:
        title: PeriodResponseBody
        type: object
        properties:
            endTime:
                type: string
                description: End time
                example: "2020-01-01T00:00:00Z"
                format: date-time
            name:
                type: string
                description: Period name
                example: Morning
            startTime:
                type: string
                description: Start time
                example: "2020-01-01T00:00:00Z"
                format: date-time
            summary:
                type: string
                description: Summary
                example: Clear
            temperature:
                type: integer
                description: Temperature
                example: 70
                format: int64
            temperatureUnit:
                type: string
                description: Temperature unit
                example: F
        description: Weather forecast period
        example:
            endTime: "2020-01-01T00:00:00Z"
            name: Morning
            startTime: "2020-01-01T00:00:00Z"
            summary: Clear
            temperature: 70
            temperatureUnit: F
        required:
            - name
            - startTime
            - endTime
            - temperature
            - temperatureUnit
            - summary
    PollerAddLocationLocationExistsResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Location already exists (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PollerAddWorkerResponseBody:
        title: PollerAddWorkerResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: Creation timestamp
                example: "2020-09-01T12:00:00Z"
            id:
                type: string
                description: Worker ID
                example: "1"
            jobs:
                type: array
                items:
                    $ref: '#/definitions/JobResponseBody'
                description: Worker poll jobs
                example:
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
        example:
            created_at: "2020-09-01T12:00:00Z"
            id: "1"
            jobs:
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
        required:
            - id
            - jobs
            - created_at
    PollerRemoveWorkerTooFewResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Only one worker left (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    PollerStatusResponseBody:
        title: PollerStatusResponseBody
        type: object
        properties:
            jobs:
                type: array
                items:
                    $ref: '#/definitions/JobResponseBody'
                description: Location poll jobs
                example:
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
            workers:
                type: array
                items:
                    $ref: '#/definitions/WorkerResponseBody'
                description: Poller workers
                example:
                    - created_at: "2020-09-01T12:00:00Z"
                      id: "1"
                      jobs:
                        - created_at: "2020-09-01T12:00:00Z"
                          key: "1"
                          payload:
                            - 123
                            - 34
                            - 115
                            - 116
                            - 97
                            - 116
                            - 101
                            - 34
                            - 58
                            - 34
                            - 67
                            - 65
                            - 34
                            - 44
                            - 34
                            - 99
                            - 105
                            - 116
                            - 121
                            - 34
                            - 58
                            - 34
                            - 83
                            - 97
                            - 110
                            - 116
                            - 97
                            - 32
                            - 66
                            - 97
                            - 114
                            - 98
                            - 97
                            - 114
                            - 97
                            - 34
                            - 125
                        - created_at: "2020-09-01T12:00:00Z"
                          key: "1"
                          payload:
                            - 123
                            - 34
                            - 115
                            - 116
                            - 97
                            - 116
                            - 101
                            - 34
                            - 58
                            - 34
                            - 67
                            - 65
                            - 34
                            - 44
                            - 34
                            - 99
                            - 105
                            - 116
                            - 121
                            - 34
                            - 58
                            - 34
                            - 83
                            - 97
                            - 110
                            - 116
                            - 97
                            - 32
                            - 66
                            - 97
                            - 114
                            - 98
                            - 97
                            - 114
                            - 97
                            - 34
                            - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      id: "1"
                      jobs:
                        - created_at: "2020-09-01T12:00:00Z"
                          key: "1"
                          payload:
                            - 123
                            - 34
                            - 115
                            - 116
                            - 97
                            - 116
                            - 101
                            - 34
                            - 58
                            - 34
                            - 67
                            - 65
                            - 34
                            - 44
                            - 34
                            - 99
                            - 105
                            - 116
                            - 121
                            - 34
                            - 58
                            - 34
                            - 83
                            - 97
                            - 110
                            - 116
                            - 97
                            - 32
                            - 66
                            - 97
                            - 114
                            - 98
                            - 97
                            - 114
                            - 97
                            - 34
                            - 125
                        - created_at: "2020-09-01T12:00:00Z"
                          key: "1"
                          payload:
                            - 123
                            - 34
                            - 115
                            - 116
                            - 97
                            - 116
                            - 101
                            - 34
                            - 58
                            - 34
                            - 67
                            - 65
                            - 34
                            - 44
                            - 34
                            - 99
                            - 105
                            - 116
                            - 121
                            - 34
                            - 58
                            - 34
                            - 83
                            - 97
                            - 110
                            - 116
                            - 97
                            - 32
                            - 66
                            - 97
                            - 114
                            - 98
                            - 97
                            - 114
                            - 97
                            - 34
                            - 125
        example:
            jobs:
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
            workers:
                - created_at: "2020-09-01T12:00:00Z"
                  id: "1"
                  jobs:
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                - created_at: "2020-09-01T12:00:00Z"
                  id: "1"
                  jobs:
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                - created_at: "2020-09-01T12:00:00Z"
                  id: "1"
                  jobs:
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
        required:
            - workers
            - jobs
    PollerSubscribeResponseBody:
        title: PollerSubscribeResponseBody
        type: object
        properties:
            location:
                $ref: '#/definitions/LocationResponseBody'
            periods:
                type: array
                items:
                    $ref: '#/definitions/PeriodResponseBody'
                description: Weather forecast periods
                example:
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
                    - endTime: "2020-01-01T00:00:00Z"
                      name: Morning
                      startTime: "2020-01-01T00:00:00Z"
                      summary: Clear
                      temperature: 70
                      temperatureUnit: F
        example:
            location:
                city: Santa Barbara
                lat: 34.4237458
                long: -119.7049146
                state: CA
            periods:
                - endTime: "2020-01-01T00:00:00Z"
                  name: Morning
                  startTime: "2020-01-01T00:00:00Z"
                  summary: Clear
                  temperature: 70
                  temperatureUnit: F
                - endTime: "2020-01-01T00:00:00Z"
                  name: Morning
                  startTime: "2020-01-01T00:00:00Z"
                  summary: Clear
                  temperature: 70
                  temperatureUnit: F
                - endTime: "2020-01-01T00:00:00Z"
                  name: Morning
                  startTime: "2020-01-01T00:00:00Z"
                  summary: Clear
                  temperature: 70
                  temperatureUnit: F
                - endTime: "2020-01-01T00:00:00Z"
                  name: Morning
                  startTime: "2020-01-01T00:00:00Z"
                  summary: Clear
                  temperature: 70
                  temperatureUnit: F
        required:
            - location
            - periods
    WorkerResponseBody:
        title: WorkerResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: Creation timestamp
                example: "2020-09-01T12:00:00Z"
            id:
                type: string
                description: Worker ID
                example: "1"
            jobs:
                type: array
                items:
                    $ref: '#/definitions/JobResponseBody'
                description: Worker poll jobs
                example:
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
                    - created_at: "2020-09-01T12:00:00Z"
                      key: "1"
                      payload:
                        - 123
                        - 34
                        - 115
                        - 116
                        - 97
                        - 116
                        - 101
                        - 34
                        - 58
                        - 34
                        - 67
                        - 65
                        - 34
                        - 44
                        - 34
                        - 99
                        - 105
                        - 116
                        - 121
                        - 34
                        - 58
                        - 34
                        - 83
                        - 97
                        - 110
                        - 116
                        - 97
                        - 32
                        - 66
                        - 97
                        - 114
                        - 98
                        - 97
                        - 114
                        - 97
                        - 34
                        - 125
        description: Poller worker
        example:
            created_at: "2020-09-01T12:00:00Z"
            id: "1"
            jobs:
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
                - created_at: "2020-09-01T12:00:00Z"
                  key: "1"
                  payload:
                    - 123
                    - 34
                    - 115
                    - 116
                    - 97
                    - 116
                    - 101
                    - 34
                    - 58
                    - 34
                    - 67
                    - 65
                    - 34
                    - 44
                    - 34
                    - 99
                    - 105
                    - 116
                    - 121
                    - 34
                    - 58
                    - 34
                    - 83
                    - 97
                    - 110
                    - 116
                    - 97
                    - 32
                    - 66
                    - 97
                    - 114
                    - 98
                    - 97
                    - 114
                    - 97
                    - 34
                    - 125
        required:
            - id
            - jobs
            - created_at
